import { useCallback, useEffect, useState } from 'react'
import { ListTree, RefreshCw } from 'lucide-react'
import { toast } from 'sonner'
import { plansApi } from '../../api/client'
import { useSpace } from '../../contexts/SpaceContext'
import { SpaceLink as Link } from '../../core/spaceNav'
import { errMsg } from '../../lib/utils'
import type { PlanSummary } from '../../types/api'
import { Badge, StatusBadge } from '../../components/ui/badge'
import { Button } from '../../components/ui/button'
import { Card } from '../../components/ui/card'
import { EmptyState } from '../../components/ui/empty-state'
import { Skeleton } from '../../components/ui/skeleton'

function fmt(value: string | null | undefined): string {
  return value ? new Date(value).toLocaleString() : '—'
}

function PlanCard({ plan }: { plan: PlanSummary }) {
  return (
    <Card className="mb-0 p-4">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <Link to={`/plans/${plan.id}`} className="font-medium hover:underline">{plan.name}</Link>
          <p className="mt-1 text-xs text-muted-foreground line-clamp-2">{plan.description ?? 'No description'}</p>
        </div>
        <StatusBadge status={plan.status} />
      </div>
      <div className="mt-3 flex flex-wrap gap-1.5">
        <Link to={`/tasks/${plan.source_task_id}`}><Badge variant="outline">Source task {plan.source_task_id.slice(0, 8)}…</Badge></Link>
        {plan.current_version && <Badge variant="outline">v{plan.current_version.version ?? '—'}</Badge>}
        {plan.current_version && <Badge variant="secondary">{plan.current_version.node_count ?? 0} nodes</Badge>}
        {plan.current_version && <Badge variant="muted">{plan.current_version.status ?? 'unknown'}</Badge>}
      </div>
      <p className="mt-3 text-xs text-muted-foreground">Updated {fmt(plan.updated_at)}</p>
    </Card>
  )
}

export default function PlansPage() {
  const { activeSpaceId, activeSpaceName } = useSpace()
  const [plans, setPlans] = useState<PlanSummary[]>([])
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    if (!activeSpaceId) {
      setPlans([])
      setLoading(false)
      return
    }
    setLoading(true)
    try {
      setPlans(await plansApi.list({ limit: 100 }))
    } catch (error) {
      toast.error(errMsg(error))
      setPlans([])
    } finally {
      setLoading(false)
    }
  }, [activeSpaceId])

  useEffect(() => { void load() }, [load])

  return (
    <div className="max-w-6xl space-y-6 p-6">
      <div className="flex flex-wrap items-start justify-between gap-4 border-b border-border pb-4">
        <div className="flex items-center gap-3">
          <div className="flex size-11 items-center justify-center rounded-xl border border-primary/35 bg-primary/10"><ListTree className="size-5 text-accent-foreground" /></div>
          <div>
            <h1 className="text-xl font-semibold tracking-tight">Agent Plans</h1>
            <p className="text-sm text-muted-foreground">Plans are generated by an Agent from a source Task and reviewed here.</p>
            <p className="text-xs text-muted-foreground">Viewing: {activeSpaceName ?? activeSpaceId ?? 'No operational space selected'}</p>
          </div>
        </div>
        <Button size="sm" variant="outline" onClick={() => void load()} disabled={loading || !activeSpaceId}><RefreshCw className={loading ? 'size-3.5 animate-spin' : 'size-3.5'} /> Refresh</Button>
      </div>
      {loading ? (
        <div className="mt-4 space-y-3"><Skeleton className="h-24 w-full" /><Skeleton className="h-24 w-full" /></div>
      ) : plans.length === 0 ? (
        <EmptyState title="No Agent plans yet" description="Open a source Task and choose Ask Agent to plan. Plans appear here after the Agent proposes them." />
      ) : (
        <div className="grid gap-3 md:grid-cols-2">{plans.map(plan => <PlanCard key={plan.id} plan={plan} />)}</div>
      )}
    </div>
  )
}
