import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const repoRoot = join(__dirname, "..", "..");

function serverServiceBlock(mode: "dev" | "test" | "prod"): string {
  const text = readFileSync(
    join(repoRoot, "ops", "compose", `docker-compose.${mode}.yml`),
    "utf8",
  );
  const start = text.indexOf("\n  server:");
  expect(start).toBeGreaterThanOrEqual(0);
  const nextService = text.indexOf("\n  frontend:", start + 1);
  return text.slice(start, nextService === -1 ? undefined : nextService);
}

function frontendServiceBlock(mode: "dev" | "test" | "prod"): string {
  const text = composeText(mode);
  const start = text.indexOf("\n  frontend:");
  expect(start).toBeGreaterThanOrEqual(0);
  const nextService = text.indexOf("\n  deployer:", start + 1);
  return text.slice(start, nextService === -1 ? undefined : nextService);
}

function composeText(mode: "dev" | "test" | "prod"): string {
  return readFileSync(
    join(repoRoot, "ops", "compose", `docker-compose.${mode}.yml`),
    "utf8",
  );
}

function deployerServiceBlock(mode: "dev" | "test" | "prod"): string {
  const text = composeText(mode);
  const start = text.indexOf("\n  deployer:");
  expect(start).toBeGreaterThanOrEqual(0);
  return text.slice(start);
}

describe("compose server config", () => {
  it("loads server credentials from .server.env and does not publish the API port", () => {
    for (const mode of ["dev", "test", "prod"] as const) {
      const block = serverServiceBlock(mode);
      // Credentials (OAuth, session, admin) are loaded from .server.env generated by start.sh.
      expect(block).toContain("env_file:");
      expect(block).toContain(".server.env");
      // The server API port is never published externally; nginx/frontend is the public face.
      expect(block).not.toContain("8010:8010");
      expect(block).not.toContain("8110:8010");
    }
  });

  it("uses the server compose service as the backend dependency", () => {
    for (const mode of ["dev", "test", "prod"] as const) {
      const text = composeText(mode);
      expect(text).toContain("\n  server:");
      expect(text).toContain("container_name: agent-space-" + mode + "-server");
    }
  });

  it("bind-mounts live server migrations for dev and test one-shot migration runs", () => {
    for (const mode of ["dev", "test"] as const) {
      const block = serverServiceBlock(mode);
      expect(block).toContain(
        "../../server/migrations:/app/server/migrations:ro",
      );
    }
    expect(serverServiceBlock("prod")).not.toContain(
      "../../server/migrations:/app/server/migrations:ro",
    );
    expect(readFileSync(join(repoRoot, "server", "Dockerfile"), "utf8")).toContain(
      "COPY server/migrations ./migrations",
    );
  });

  it("keeps official plugin source out of the production server container", () => {
    for (const mode of ["dev", "test"] as const) {
      expect(serverServiceBlock(mode)).toContain("../../plugins:/app/plugins:ro");
    }
    expect(serverServiceBlock("prod")).not.toContain("../../plugins:");
    expect(readFileSync(join(repoRoot, "server", "Dockerfile"), "utf8")).toContain(
      "COPY plugins /app/plugins",
    );
  });

  it("builds the frontend from the repo root so official plugin pages are included", () => {
    for (const mode of ["dev", "test", "prod"] as const) {
      const block = frontendServiceBlock(mode);
      expect(block).toContain("context: ../../");
      expect(block).toContain("dockerfile: apps/web/Dockerfile");
    }
    for (const mode of ["dev", "test"] as const) {
      const block = frontendServiceBlock(mode);
      expect(block).toContain("../../apps/web:/repo/apps/web");
      expect(block).toContain("../../plugins:/repo/plugins:ro");
    }
  });

  it("keeps the privileged deployer socket private to the deployer container", () => {
    for (const mode of ["dev", "test", "prod"] as const) {
      expect(deployerServiceBlock(mode)).toContain(
        "DEPLOYER_SOCKET=/tmp/agent-space-deployer.sock",
      );
      expect(serverServiceBlock(mode)).not.toContain("deployer.sock");
    }
  });
});
