import {
  pgTable,
  index,
  unique,
  foreignKey,
  varchar,
  text,
  integer,
  doublePrecision,
  jsonb,
  timestamp,
  type PgTableExtraConfigValue,
} from "drizzle-orm/pg-core";
import { spaces } from "./spaces";
import { users } from "./auth";
import { agents } from "./agents";
import { projects } from "./projects";
import { workspaces } from "./workspaces";
import { tasks } from "./tasks";
import { runs } from "./runs";

export const plans = pgTable("plans", {
  id: varchar({ length: 36 }).primaryKey().notNull(),
  spaceId: varchar("space_id", { length: 36 }).notNull(),
  workspaceId: varchar("workspace_id", { length: 36 }),
  projectId: varchar("project_id", { length: 36 }),
  sourceTaskId: varchar("source_task_id", { length: 36 }).notNull(),
  rootRunId: varchar("root_run_id", { length: 36 }),
  currentPlanVersionId: varchar("current_plan_version_id", { length: 36 }),
  name: varchar({ length: 512 }).notNull(),
  description: text(),
  status: varchar({ length: 32 }).default("draft").notNull(),
  createdByUserId: varchar("created_by_user_id", { length: 36 }),
  createdByAgentId: varchar("created_by_agent_id", { length: 36 }),
  metadataJson: jsonb("metadata_json").default({}).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table): PgTableExtraConfigValue[] => [
  index("ix_plans_space_status_updated").using("btree", table.spaceId.asc().nullsLast(), table.status.asc().nullsLast(), table.updatedAt.desc().nullsLast()),
  index("ix_plans_source_task_id").using("btree", table.sourceTaskId.asc().nullsLast()),
  index("ix_plans_root_run_id").using("btree", table.rootRunId.asc().nullsLast()),
  unique("uq_plans_source_task_id").on(table.sourceTaskId),
  unique("uq_plans_id_space_id").on(table.id, table.spaceId),
  foreignKey({ columns: [table.spaceId], foreignColumns: [spaces.id], name: "plans_space_id_fkey" }),
  foreignKey({ columns: [table.workspaceId, table.spaceId], foreignColumns: [workspaces.id, workspaces.spaceId], name: "plans_workspace_id_fkey" }),
  foreignKey({ columns: [table.projectId, table.spaceId], foreignColumns: [projects.id, projects.spaceId], name: "plans_project_id_fkey" }).onDelete("set null"),
  foreignKey({ columns: [table.sourceTaskId, table.spaceId], foreignColumns: [tasks.id, tasks.spaceId], name: "plans_source_task_space_fkey" }),
  foreignKey({ columns: [table.createdByUserId], foreignColumns: [users.id], name: "plans_created_by_user_id_fkey" }),
  foreignKey({ columns: [table.createdByAgentId], foreignColumns: [agents.id], name: "plans_created_by_agent_id_fkey" }),
]);

export const planVersions = pgTable("plan_versions", {
  id: varchar({ length: 36 }).primaryKey().notNull(),
  spaceId: varchar("space_id", { length: 36 }).notNull(),
  planId: varchar("plan_id", { length: 36 }).notNull(),
  version: integer().notNull(),
  referenceWorkflowVersionId: varchar("reference_workflow_version_id", { length: 36 }),
  plannerMode: varchar("planner_mode", { length: 32 }).default("agent").notNull(),
  status: varchar({ length: 32 }).default("draft").notNull(),
  approvalProposalId: varchar("approval_proposal_id", { length: 36 }),
  planningRunId: varchar("planning_run_id", { length: 36 }),
  planningToolCallId: varchar("planning_tool_call_id", { length: 256 }),
  nodeCount: integer("node_count").notNull(),
  depth: integer().notNull(),
  budgetJson: jsonb("budget_json").default({}).notNull(),
  definitionJson: jsonb("definition_json").notNull(),
  createdByUserId: varchar("created_by_user_id", { length: 36 }),
  createdByAgentId: varchar("created_by_agent_id", { length: 36 }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table): PgTableExtraConfigValue[] => [
  index("ix_plan_versions_space_status").using("btree", table.spaceId.asc().nullsLast(), table.status.asc().nullsLast()),
  index("ix_plan_versions_plan_id").using("btree", table.planId.asc().nullsLast(), table.version.desc().nullsLast()),
  unique("uq_plan_versions_plan_version").on(table.planId, table.version),
  unique("uq_plan_versions_id_space_id").on(table.id, table.spaceId),
  unique("uq_plan_versions_planning_call").on(table.planningRunId, table.planningToolCallId),
  foreignKey({ columns: [table.planId, table.spaceId], foreignColumns: [plans.id, plans.spaceId], name: "plan_versions_plan_space_fkey" }),
  foreignKey({ columns: [table.spaceId], foreignColumns: [spaces.id], name: "plan_versions_space_id_fkey" }),
  foreignKey({ columns: [table.createdByUserId], foreignColumns: [users.id], name: "plan_versions_created_by_user_id_fkey" }),
  foreignKey({ columns: [table.createdByAgentId], foreignColumns: [agents.id], name: "plan_versions_created_by_agent_id_fkey" }),
  foreignKey({ columns: [table.planningRunId, table.spaceId], foreignColumns: [runs.id, runs.spaceId], name: "plan_versions_planning_run_space_fkey" }),
]);

export const planNodes = pgTable("plan_nodes", {
  id: varchar({ length: 36 }).primaryKey().notNull(),
  spaceId: varchar("space_id", { length: 36 }).notNull(),
  planVersionId: varchar("plan_version_id", { length: 36 }).notNull(),
  nodeKey: varchar("node_key", { length: 128 }).notNull(),
  nodeKind: varchar("node_kind", { length: 32 }).notNull(),
  title: varchar({ length: 512 }).notNull(),
  description: text(),
  status: varchar({ length: 64 }).default("inbox").notNull(),
  assignedAgentId: varchar("assigned_agent_id", { length: 36 }),
  runtimeProfileId: varchar("runtime_profile_id", { length: 36 }),
  capabilityId: varchar("capability_id", { length: 128 }),
  promptAssetKey: varchar("prompt_asset_key", { length: 256 }),
  riskLevel: varchar("risk_level", { length: 32 }).default("low").notNull(),
  acceptanceCriteriaJson: jsonb("acceptance_criteria_json"),
  definitionOfDone: text("definition_of_done"),
  requiredOutputsJson: jsonb("required_outputs_json"),
  maxRuns: integer("max_runs"),
  maxCost: doublePrecision("max_cost"),
  maxDurationSeconds: integer("max_duration_seconds"),
  policyJson: jsonb("policy_json"),
  verificationRecipeRefsJson: jsonb("verification_recipe_refs_json").default([]).notNull(),
  metadataJson: jsonb("metadata_json").default({}).notNull(),
  blockedReason: text("blocked_reason"),
  contentHash: varchar("content_hash", { length: 128 }).notNull(),
  approvalProposalId: varchar("approval_proposal_id", { length: 36 }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table): PgTableExtraConfigValue[] => [
  index("ix_plan_nodes_space_version_status").using("btree", table.spaceId.asc().nullsLast(), table.planVersionId.asc().nullsLast(), table.status.asc().nullsLast()),
  index("ix_plan_nodes_assigned_agent").using("btree", table.spaceId.asc().nullsLast(), table.assignedAgentId.asc().nullsLast()),
  index("ix_plan_nodes_capability").using("btree", table.spaceId.asc().nullsLast(), table.capabilityId.asc().nullsLast()),
  unique("uq_plan_nodes_version_key").on(table.planVersionId, table.nodeKey),
  unique("uq_plan_nodes_id_space").on(table.id, table.spaceId),
  foreignKey({ columns: [table.planVersionId, table.spaceId], foreignColumns: [planVersions.id, planVersions.spaceId], name: "plan_nodes_version_space_fkey" }),
  foreignKey({ columns: [table.assignedAgentId, table.spaceId], foreignColumns: [agents.id, agents.spaceId], name: "plan_nodes_assigned_agent_space_fkey" }).onDelete("set null"),
  foreignKey({ columns: [table.spaceId], foreignColumns: [spaces.id], name: "plan_nodes_space_id_fkey" }),
]);

export const planNodeDependencies = pgTable("plan_node_dependencies", {
  id: varchar({ length: 36 }).primaryKey().notNull(),
  spaceId: varchar("space_id", { length: 36 }).notNull(),
  planVersionId: varchar("plan_version_id", { length: 36 }).notNull(),
  nodeId: varchar("node_id", { length: 36 }).notNull(),
  dependsOnNodeId: varchar("depends_on_node_id", { length: 36 }).notNull(),
  dependencyType: varchar("dependency_type", { length: 32 }).default("requires").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table): PgTableExtraConfigValue[] => [
  index("ix_plan_node_dependencies_node").using("btree", table.spaceId.asc().nullsLast(), table.nodeId.asc().nullsLast()),
  index("ix_plan_node_dependencies_depends_on").using("btree", table.spaceId.asc().nullsLast(), table.dependsOnNodeId.asc().nullsLast()),
  unique("uq_plan_node_dependencies_edge").on(table.nodeId, table.dependsOnNodeId),
  foreignKey({ columns: [table.planVersionId, table.spaceId], foreignColumns: [planVersions.id, planVersions.spaceId], name: "plan_node_dependencies_version_space_fkey" }),
  foreignKey({ columns: [table.nodeId, table.spaceId], foreignColumns: [planNodes.id, planNodes.spaceId], name: "plan_node_dependencies_node_space_fkey" }),
  foreignKey({ columns: [table.dependsOnNodeId, table.spaceId], foreignColumns: [planNodes.id, planNodes.spaceId], name: "plan_node_dependencies_depends_on_space_fkey" }),
  foreignKey({ columns: [table.spaceId], foreignColumns: [spaces.id], name: "plan_node_dependencies_space_id_fkey" }),
]);

export const planNodeRuns = pgTable("plan_node_runs", {
  id: varchar({ length: 36 }).primaryKey().notNull(),
  spaceId: varchar("space_id", { length: 36 }).notNull(),
  planNodeId: varchar("plan_node_id", { length: 36 }).notNull(),
  runId: varchar("run_id", { length: 36 }).notNull(),
  role: varchar("role", { length: 32 }).default("primary").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table): PgTableExtraConfigValue[] => [
  index("ix_plan_node_runs_node").using("btree", table.spaceId.asc().nullsLast(), table.planNodeId.asc().nullsLast()),
  index("ix_plan_node_runs_run").using("btree", table.spaceId.asc().nullsLast(), table.runId.asc().nullsLast()),
  unique("uq_plan_node_runs_node_run").on(table.planNodeId, table.runId),
  foreignKey({ columns: [table.planNodeId, table.spaceId], foreignColumns: [planNodes.id, planNodes.spaceId], name: "plan_node_runs_node_space_fkey" }),
  foreignKey({ columns: [table.runId, table.spaceId], foreignColumns: [runs.id, runs.spaceId], name: "plan_node_runs_run_space_fkey" }),
  foreignKey({ columns: [table.spaceId], foreignColumns: [spaces.id], name: "plan_node_runs_space_id_fkey" }),
]);
