import {
	index,
	unique,
	uniqueIndex,
	check,
	foreignKey,
	pgTable,
	varchar,
	text,
	integer,
	jsonb,
	numeric,
	timestamp,
	type PgTableExtraConfigValue,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { agents, cliCredentialProfiles } from "./agents";
import { users } from "./auth";
import { modelProviders } from "./providers";
import { projects } from "./projects";
import { runs } from "./runs";
import { sessions } from "./sessions";
import { spaces } from "./spaces";
import { workspaces } from "./workspaces";

export const instanceIdentity = pgTable("instance_identity", {
	id: varchar({ length: 32 }).primaryKey().notNull(),
	instanceId: varchar("instance_id", { length: 36 }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table): PgTableExtraConfigValue[] => [
	unique("uq_instance_identity_instance_id").on(table.instanceId),
	check("ck_instance_identity_singleton", sql`(id)::text = 'local'::text`),
]);

export const usageImportBatches = pgTable("usage_import_batches", {
	id: varchar({ length: 36 }).primaryKey().notNull(),
	instanceId: varchar("instance_id", { length: 36 }).notNull(),
	targetSpaceId: varchar("target_space_id", { length: 36 }).notNull(),
	ownerUserId: varchar("owner_user_id", { length: 36 }).notNull(),
	sourceType: varchar("source_type", { length: 64 }).notNull(),
	sourceKind: varchar("source_kind", { length: 64 }).notNull(),
	status: varchar({ length: 32 }).notNull(),
	startedAt: timestamp("started_at", { withTimezone: true, mode: "string" }),
	completedAt: timestamp("completed_at", { withTimezone: true, mode: "string" }),
	sourceFingerprint: varchar("source_fingerprint", { length: 256 }),
	previewSummaryJson: jsonb("preview_summary_json").default({}).notNull(),
	importSummaryJson: jsonb("import_summary_json").default({}).notNull(),
	errorJson: jsonb("error_json"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table): PgTableExtraConfigValue[] => [
	index("ix_usage_import_batches_instance_id").using("btree", table.instanceId.asc().nullsLast()),
	index("ix_usage_import_batches_target_space_id").using("btree", table.targetSpaceId.asc().nullsLast()),
	index("ix_usage_import_batches_owner_user_id").using("btree", table.ownerUserId.asc().nullsLast()),
	foreignKey({
		columns: [table.targetSpaceId],
		foreignColumns: [spaces.id],
		name: "usage_import_batches_target_space_id_fkey",
	}).onDelete("cascade"),
	foreignKey({
		columns: [table.ownerUserId],
		foreignColumns: [users.id],
		name: "usage_import_batches_owner_user_id_fkey",
	}),
	check("ck_usage_import_batches_source_type", sql`(source_type)::text = ANY (ARRAY[('claude_code_history'::character varying)::text, ('codex_cli_history'::character varying)::text, ('cross_instance_bundle'::character varying)::text, ('manual_usage_csv'::character varying)::text])`),
	check("ck_usage_import_batches_source_kind", sql`(source_kind)::text = ANY (ARRAY[('managed_profile'::character varying)::text, ('uploaded_archive'::character varying)::text, ('server_path'::character varying)::text, ('scanner_manifest'::character varying)::text, ('remote_bundle'::character varying)::text])`),
	check("ck_usage_import_batches_status", sql`(status)::text = ANY (ARRAY[('previewed'::character varying)::text, ('importing'::character varying)::text, ('completed'::character varying)::text, ('failed'::character varying)::text, ('cancelled'::character varying)::text])`),
]);

export const modelPricingRules = pgTable("model_pricing_rules", {
	id: varchar({ length: 36 }).primaryKey().notNull(),
	scopeType: varchar("scope_type", { length: 32 }).notNull(),
	spaceId: varchar("space_id", { length: 36 }),
	providerType: varchar("provider_type", { length: 64 }),
	providerId: varchar("provider_id", { length: 36 }),
	modelPattern: varchar("model_pattern", { length: 256 }).notNull(),
	inputUsdPerMillion: numeric("input_usd_per_million", { precision: 18, scale: 8 }),
	outputUsdPerMillion: numeric("output_usd_per_million", { precision: 18, scale: 8 }),
	cacheWriteUsdPerMillion: numeric("cache_write_usd_per_million", { precision: 18, scale: 8 }),
	cacheReadUsdPerMillion: numeric("cache_read_usd_per_million", { precision: 18, scale: 8 }),
	reasoningUsdPerMillion: numeric("reasoning_usd_per_million", { precision: 18, scale: 8 }),
	usageTypePricesJson: jsonb("usage_type_prices_json").default({}).notNull(),
	tierConditionsJson: jsonb("tier_conditions_json").default({}).notNull(),
	priority: integer().default(0).notNull(),
	pricingNormalizationVersion: integer("pricing_normalization_version").default(1).notNull(),
	currency: varchar({ length: 8 }).default("USD").notNull(),
	effectiveFrom: timestamp("effective_from", { withTimezone: true, mode: "string" }).notNull(),
	effectiveUntil: timestamp("effective_until", { withTimezone: true, mode: "string" }),
	source: varchar({ length: 32 }).notNull(),
	metadataJson: jsonb("metadata_json").default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table): PgTableExtraConfigValue[] => [
	index("ix_model_pricing_rules_effective").using("btree", table.effectiveFrom.asc().nullsLast(), table.effectiveUntil.asc().nullsLast()),
	index("ix_model_pricing_rules_scope").using("btree", table.scopeType.asc().nullsLast(), table.spaceId.asc().nullsLast()),
	index("ix_model_pricing_rules_provider_model").using("btree", table.providerId.asc().nullsLast(), table.providerType.asc().nullsLast(), table.modelPattern.asc().nullsLast(), table.priority.asc().nullsLast()),
	foreignKey({
		columns: [table.spaceId],
		foreignColumns: [spaces.id],
		name: "model_pricing_rules_space_id_fkey",
	}).onDelete("cascade"),
	foreignKey({
		columns: [table.providerId],
		foreignColumns: [modelProviders.id],
		name: "model_pricing_rules_provider_id_fkey",
	}).onDelete("set null"),
	check("ck_model_pricing_rules_scope_type", sql`(scope_type)::text = ANY (ARRAY[('system'::character varying)::text, ('instance'::character varying)::text, ('space'::character varying)::text])`),
	check("ck_model_pricing_rules_scope_space", sql`((scope_type)::text = 'space'::text AND space_id IS NOT NULL) OR ((scope_type)::text <> 'space'::text AND space_id IS NULL)`),
	check("ck_model_pricing_rules_source", sql`(source)::text = ANY (ARRAY[('built_in'::character varying)::text, ('instance_admin'::character varying)::text, ('space_admin'::character varying)::text, ('imported'::character varying)::text])`),
	check("ck_model_pricing_rules_effective_window", sql`effective_until IS NULL OR effective_until > effective_from`),
	check("ck_model_pricing_rules_nonnegative_prices", sql`(input_usd_per_million IS NULL OR input_usd_per_million >= 0) AND (output_usd_per_million IS NULL OR output_usd_per_million >= 0) AND (cache_write_usd_per_million IS NULL OR cache_write_usd_per_million >= 0) AND (cache_read_usd_per_million IS NULL OR cache_read_usd_per_million >= 0) AND (reasoning_usd_per_million IS NULL OR reasoning_usd_per_million >= 0)`),
]);

export const tokenUsageEvents = pgTable("token_usage_events", {
	id: varchar({ length: 36 }).primaryKey().notNull(),
	instanceId: varchar("instance_id", { length: 36 }).notNull(),
	reportingInstanceId: varchar("reporting_instance_id", { length: 36 }).notNull(),
	originInstanceId: varchar("origin_instance_id", { length: 36 }).notNull(),
	spaceId: varchar("space_id", { length: 36 }).notNull(),
	ownerUserId: varchar("owner_user_id", { length: 36 }),
	visibility: varchar({ length: 32 }).notNull(),
	accessLevel: varchar("access_level", { length: 16 }).notNull(),
	originSpaceId: varchar("origin_space_id", { length: 128 }),
	eventType: varchar("event_type", { length: 64 }).notNull(),
	sourceType: varchar("source_type", { length: 64 }).notNull(),
	sourceResourceType: varchar("source_resource_type", { length: 64 }),
	sourceResourceId: varchar("source_resource_id", { length: 36 }),
	executionChannel: varchar("execution_channel", { length: 64 }).notNull(),
	meterSubjectType: varchar("meter_subject_type", { length: 64 }).notNull(),
	meterSubjectId: varchar("meter_subject_id", { length: 128 }).notNull(),
	subjectUserId: varchar("subject_user_id", { length: 36 }),
	subjectTeamId: varchar("subject_team_id", { length: 36 }),
	adapterType: varchar("adapter_type", { length: 64 }),
	runtimeToolVersion: varchar("runtime_tool_version", { length: 128 }),
	providerId: varchar("provider_id", { length: 36 }),
	providerType: varchar("provider_type", { length: 64 }),
	providerNameSnapshot: varchar("provider_name_snapshot", { length: 256 }),
	vendor: varchar({ length: 64 }),
	model: varchar({ length: 256 }),
	task: varchar({ length: 128 }),
	runId: varchar("run_id", { length: 36 }),
	rootRunId: varchar("root_run_id", { length: 36 }),
	parentRunId: varchar("parent_run_id", { length: 36 }),
	runGroupId: varchar("run_group_id", { length: 36 }),
	sessionId: varchar("session_id", { length: 36 }),
	externalSessionId: varchar("external_session_id", { length: 256 }),
	sessionPath: text("session_path"),
	sessionName: varchar("session_name", { length: 256 }),
	agentId: varchar("agent_id", { length: 36 }),
	projectId: varchar("project_id", { length: 36 }),
	workspaceId: varchar("workspace_id", { length: 36 }),
	triggerOrigin: varchar("trigger_origin", { length: 64 }),
	occurredAt: timestamp("occurred_at", { withTimezone: true, mode: "string" }).notNull(),
	recordedAt: timestamp("recorded_at", { withTimezone: true, mode: "string" }).notNull(),
	inputTokens: integer("input_tokens").default(0).notNull(),
	outputTokens: integer("output_tokens").default(0).notNull(),
	totalTokens: integer("total_tokens"),
	cacheCreationInputTokens: integer("cache_creation_input_tokens").default(0).notNull(),
	cacheReadInputTokens: integer("cache_read_input_tokens").default(0).notNull(),
	reasoningTokens: integer("reasoning_tokens").default(0).notNull(),
	requestCount: integer("request_count").default(1).notNull(),
	estimatedCostUsd: numeric("estimated_cost_usd", { precision: 18, scale: 8 }),
	usageSchema: varchar("usage_schema", { length: 64 }).notNull(),
	usageDetailsJson: jsonb("usage_details_json").default({}).notNull(),
	costDetailsJson: jsonb("cost_details_json").default({}).notNull(),
	providerUsageJson: jsonb("provider_usage_json").default({}).notNull(),
	usageNormalizationVersion: integer("usage_normalization_version").default(1).notNull(),
	totalTokensSource: varchar("total_tokens_source", { length: 32 }).notNull(),
	currency: varchar({ length: 8 }).default("USD").notNull(),
	pricingRuleId: varchar("pricing_rule_id", { length: 36 }),
	pricingTierName: varchar("pricing_tier_name", { length: 128 }),
	dimensionsJson: jsonb("dimensions_json").default({}).notNull(),
	usageAccuracy: varchar("usage_accuracy", { length: 32 }).notNull(),
	dedupeConfidence: varchar("dedupe_confidence", { length: 32 }).notNull(),
	importBatchId: varchar("import_batch_id", { length: 36 }),
	idempotencyKey: varchar("idempotency_key", { length: 256 }).notNull(),
	metadataJson: jsonb("metadata_json").default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table): PgTableExtraConfigValue[] => [
	unique("uq_token_usage_events_space_idempotency").on(table.spaceId, table.idempotencyKey),
	index("ix_token_usage_events_space_occurred").using("btree", table.spaceId.asc().nullsLast(), table.occurredAt.asc().nullsLast()),
	index("ix_token_usage_events_instance_occurred").using("btree", table.instanceId.asc().nullsLast(), table.occurredAt.asc().nullsLast()),
	index("ix_token_usage_events_provider_model").using("btree", table.spaceId.asc().nullsLast(), table.providerId.asc().nullsLast(), table.model.asc().nullsLast(), table.occurredAt.asc().nullsLast()),
	index("ix_token_usage_events_channel_adapter").using("btree", table.spaceId.asc().nullsLast(), table.executionChannel.asc().nullsLast(), table.adapterType.asc().nullsLast(), table.occurredAt.asc().nullsLast()),
	index("ix_token_usage_events_session").using("btree", table.spaceId.asc().nullsLast(), table.sessionId.asc().nullsLast(), table.occurredAt.asc().nullsLast()),
	index("ix_token_usage_events_external_session").using("btree", table.spaceId.asc().nullsLast(), table.externalSessionId.asc().nullsLast(), table.occurredAt.asc().nullsLast()),
	index("ix_token_usage_events_run_id").using("btree", table.spaceId.asc().nullsLast(), table.runId.asc().nullsLast()),
	index("ix_token_usage_events_owner_occurred").using("btree", table.spaceId.asc().nullsLast(), table.ownerUserId.asc().nullsLast(), table.occurredAt.asc().nullsLast()),
	index("ix_token_usage_events_visibility_occurred").using("btree", table.spaceId.asc().nullsLast(), table.visibility.asc().nullsLast(), table.occurredAt.asc().nullsLast()),
	index("ix_token_usage_events_source_resource").using("btree", table.spaceId.asc().nullsLast(), table.sourceResourceType.asc().nullsLast(), table.sourceResourceId.asc().nullsLast()),
	index("ix_token_usage_events_import_batch_id").using("btree", table.importBatchId.asc().nullsLast()),
	foreignKey({
		columns: [table.spaceId],
		foreignColumns: [spaces.id],
		name: "token_usage_events_space_id_fkey",
	}).onDelete("cascade"),
	foreignKey({
		columns: [table.ownerUserId],
		foreignColumns: [users.id],
		name: "token_usage_events_owner_user_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.subjectUserId],
		foreignColumns: [users.id],
		name: "token_usage_events_subject_user_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.providerId],
		foreignColumns: [modelProviders.id],
		name: "token_usage_events_provider_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.runId],
		foreignColumns: [runs.id],
		name: "token_usage_events_run_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.rootRunId],
		foreignColumns: [runs.id],
		name: "token_usage_events_root_run_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.parentRunId],
		foreignColumns: [runs.id],
		name: "token_usage_events_parent_run_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.sessionId],
		foreignColumns: [sessions.id],
		name: "token_usage_events_session_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.agentId],
		foreignColumns: [agents.id],
		name: "token_usage_events_agent_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.projectId],
		foreignColumns: [projects.id],
		name: "token_usage_events_project_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.workspaceId],
		foreignColumns: [workspaces.id],
		name: "token_usage_events_workspace_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.importBatchId],
		foreignColumns: [usageImportBatches.id],
		name: "token_usage_events_import_batch_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.pricingRuleId],
		foreignColumns: [modelPricingRules.id],
		name: "token_usage_events_pricing_rule_id_fkey",
	}).onDelete("set null"),
	check("ck_token_usage_events_source_type", sql`(source_type)::text = ANY (ARRAY[('local_run'::character varying)::text, ('provider_proxy'::character varying)::text, ('cli_history_import'::character varying)::text, ('cross_instance_import'::character varying)::text, ('manual_import'::character varying)::text])`),
	check("ck_token_usage_events_event_type", sql`(event_type)::text = ANY (ARRAY[('llm.generation'::character varying)::text, ('llm.embedding'::character varying)::text, ('llm.rerank'::character varying)::text, ('cli.history_usage'::character varying)::text, ('usage.adjustment'::character varying)::text])`),
	check("ck_token_usage_events_execution_channel", sql`(execution_channel)::text = ANY (ARRAY[('managed_api'::character varying)::text, ('provider_proxy'::character varying)::text, ('local_cli_transcript'::character varying)::text, ('manual_import'::character varying)::text, ('cross_instance_import'::character varying)::text, ('unknown'::character varying)::text])`),
	check("ck_token_usage_events_total_tokens_source", sql`(total_tokens_source)::text = ANY (ARRAY[('provider_total'::character varying)::text, ('sum_of_buckets'::character varying)::text, ('estimated'::character varying)::text, ('unknown'::character varying)::text])`),
	check("ck_token_usage_events_usage_accuracy", sql`(usage_accuracy)::text = ANY (ARRAY[('provider_reported'::character varying)::text, ('proxy_observed'::character varying)::text, ('transcript_lower_bound'::character varying)::text, ('estimated'::character varying)::text, ('quota_snapshot'::character varying)::text, ('unknown'::character varying)::text])`),
	check("ck_token_usage_events_dedupe_confidence", sql`(dedupe_confidence)::text = ANY (ARRAY[('high'::character varying)::text, ('medium'::character varying)::text, ('low'::character varying)::text])`),
	check("ck_token_usage_events_visibility", sql`visibility IN ('private', 'space_shared', 'selected_users')`),
	check("ck_token_usage_events_access_level", sql`access_level IN ('full', 'summary')`),
	check("ck_token_usage_events_source_resource", sql`(source_resource_type IS NULL) = (source_resource_id IS NULL)`),
	check("ck_token_usage_events_private_owner", sql`visibility <> 'private' OR owner_user_id IS NOT NULL`),
	check("ck_token_usage_events_nonnegative_counts", sql`input_tokens >= 0 AND output_tokens >= 0 AND cache_creation_input_tokens >= 0 AND cache_read_input_tokens >= 0 AND reasoning_tokens >= 0 AND request_count >= 0 AND (total_tokens IS NULL OR total_tokens >= 0)`),
]);

export const cliUsageImportCursors = pgTable("cli_usage_import_cursors", {
	id: varchar({ length: 36 }).primaryKey().notNull(),
	instanceId: varchar("instance_id", { length: 36 }).notNull(),
	spaceId: varchar("space_id", { length: 36 }).notNull(),
	userId: varchar("user_id", { length: 36 }),
	runtime: varchar({ length: 64 }).notNull(),
	credentialProfileId: varchar("credential_profile_id", { length: 36 }),
	sourceFingerprint: varchar("source_fingerprint", { length: 256 }).notNull(),
	cursorJson: jsonb("cursor_json").default({}).notNull(),
	lastScannedAt: timestamp("last_scanned_at", { withTimezone: true, mode: "string" }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table): PgTableExtraConfigValue[] => [
	uniqueIndex("uq_cli_usage_import_cursors_scope").using("btree", table.instanceId.asc().nullsLast(), table.spaceId.asc().nullsLast(), sql`COALESCE(user_id, '__none__'::character varying)`, table.runtime.asc().nullsLast(), sql`COALESCE(credential_profile_id, '__none__'::character varying)`, table.sourceFingerprint.asc().nullsLast()),
	index("ix_cli_usage_import_cursors_space_runtime").using("btree", table.spaceId.asc().nullsLast(), table.runtime.asc().nullsLast()),
	index("ix_cli_usage_import_cursors_credential_profile").using("btree", table.credentialProfileId.asc().nullsLast()),
	foreignKey({
		columns: [table.spaceId],
		foreignColumns: [spaces.id],
		name: "cli_usage_import_cursors_space_id_fkey",
	}).onDelete("cascade"),
	foreignKey({
		columns: [table.userId],
		foreignColumns: [users.id],
		name: "cli_usage_import_cursors_user_id_fkey",
	}).onDelete("set null"),
	foreignKey({
		columns: [table.credentialProfileId],
		foreignColumns: [cliCredentialProfiles.id],
		name: "cli_usage_import_cursors_credential_profile_id_fkey",
	}).onDelete("set null"),
]);
